- id: '1759198077344'
  alias: 放电
  description: ''
  triggers:
  - trigger: time
    at: '10:14:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  conditions: []
  actions:
  - domain: marstek
    type: discharge
    device_id: cb70fec0df1d38ddf5d5aa56f4ca5bbf
  mode: single
- id: '1759198520518'
  alias: 充电
  description: ''
  triggers:
  - trigger: time
    at: '10:19:00'
    weekday:
    - tue
    - wed
    - mon
  conditions: []
  actions:
  - domain: marstek
    type: charge
    device_id: cb70fec0df1d38ddf5d5aa56f4ca5bbf
  mode: single
- id: '1759198669671'
  alias: 停止
  description: ''
  triggers:
  - trigger: time
    at: '10:18:00'
    weekday:
    - tue
    - wed
    - mon
  conditions: []
  actions:
  - domain: marstek
    type: stop
    device_id: cb70fec0df1d38ddf5d5aa56f4ca5bbf
  mode: single
